### ISSUE TITLE
Créer des Utilisateurs en base

### ISSUE THREAD

**Issue by anthonyjlmorel** [anthonyjlmorel/innomed360#19]
Associé à un hôpital/site
Et un rôle: Modérateur/Client

Nom/prénom et mot de passe (pas de SHA1/SHA2 pour le hash des mots de passe :) )

Voir ici les droits de chacun des [rôles](https://drive.google.com/drive/folders/1-DkIpKMUxUUFuMnQzAMFD4kQfjnJe6J7)

Faire un écran de login pour s'authentifier

Contrôler à chaque entrée API que l'utilisateur a les droits pour l'utiliser

Pour ce, gérer des cookies (pas de JWT).

**Comment by yroffin** [comment]
je resume ... on fait une api de sign ... avec nom/mdp validé en bdd ... et on genère un JWT ?

**Comment by anthonyjlmorel** [comment]
Alors si tu parles d'un Json Web Token, je préfère faire une gestion de cookie, plus safe (j'ai mis à jour).

Il faudrait pouvoir configurer le cookie en mode httpOnly et secure à true quand on passe en https

**Comment by yroffin** [comment]
mouais ... comme tu veux c'est toi le chef
mais bon j'ai mas la main sur le deploiement ...

JWT ça reste bien mieux que le cookie ...

**Comment by anthonyjlmorel** [comment]
Je clôture celle là, j'en ouvre une autre pour le contrôle de l'authentification à chaque entrée de l'API.
